# Generated by Django 4.2.7 on 2026-02-26 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notices', '0003_notice_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('ALL', 'All'), ('INSTITUTION', 'Institution')], default='ALL', max_length=15),
        ),
        migrations.AlterField(
            model_name='notice',
            name='department_type',
            field=models.CharField(blank=True, choices=[('Your Department', 'Your Department'), ('Institution', 'Institution'), ('Other Department', 'Other Department')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='notice',
            name='priority_score',
            field=models.FloatField(default=0.0),
        ),
    ]
