# Generated by Django 4.2.7 on 2026-03-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_alter_notice_created_by_alter_notice_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_NOTICE', 'New Notice'), ('DEADLINE', 'Deadline Reminder'), ('BROADCAST', 'Broadcast'), ('APPROVED', 'Notice Approved'), ('REJECTED', 'Notice Rejected'), ('SYSTEM', 'System Message'), ('STUDENT_REG', 'New Student Registration')], default='NEW_NOTICE', max_length=20),
        ),
    ]
