# Generated by Django 4.2.7 on 2026-04-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_seed_default_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=64)),
                ('reminder_date', models.CharField(max_length=10)),
                ('reminder_time', models.CharField(max_length=5)),
                ('reminder_note', models.TextField()),
                ('status', models.CharField(choices=[('unsent', 'Unsent'), ('sent', 'Sent'), ('completed', 'Completed')], default='unsent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staff_reminders',
                'ordering': ['reminder_date', 'reminder_time'],
            },
        ),
    ]
