# Generated by Django 4.2.7 on 2026-04-28 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffloginactivity',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='staffloginactivity',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staffloginactivity',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='staffloginactivity',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffloginactivity',
            name='login_status',
            field=models.CharField(default='SUCCESS', max_length=10),
        ),
        migrations.AddField(
            model_name='staffloginactivity',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='staffloginactivity',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='staffloginactivity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='staffloginactivity',
            index=models.Index(fields=['staff_id', 'login_time'], name='staff_login_staff_id_login_ti_idx'),
        ),
        migrations.AddIndex(
            model_name='staffloginactivity',
            index=models.Index(fields=['login_time'], name='staff_login_login_ti_idx'),
        ),
    ]
