# Generated by Django 4.2.7 on 2026-04-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_update_staffloginactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffloginactivity',
            new_name='staff_login_staff_i_3df0f2_idx',
            old_name='staff_login_staff_id_login_ti_idx',
        ),
        migrations.RenameIndex(
            model_name='staffloginactivity',
            new_name='staff_login_login_t_303cd5_idx',
            old_name='staff_login_login_ti_idx',
        ),
    ]
