# Generated by Django 4.2.7 on 2026-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_rename_staff_login_staff_id_login_ti_idx_staff_login_staff_i_3df0f2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffloginactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
