# Generated by Django 4.2.7 on 2026-05-01 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], max_length=20)),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', 'Final Year')], max_length=5)),
                ('section', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timetable_batches',
                'ordering': ['-created_at'],
                'unique_together': {('department', 'year', 'section')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('slot_start', models.IntegerField()),
                ('slot_end', models.IntegerField()),
                ('subject_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_name', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_type', models.CharField(choices=[('SUBJECT', 'Subject'), ('BREAK', 'Break'), ('LUNCH', 'Lunch'), ('LAB', 'Laboratory')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetablebatch')),
            ],
            options={
                'db_table': 'timetable_entries',
                'ordering': ['day', 'slot_start'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('NORMAL', 'Normal'), ('BREAK', 'Break'), ('LUNCH', 'Lunch')], default='NORMAL', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='timetable.timetablebatch')),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['slot_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Laboratory')], max_length=20)),
                ('staff_name', models.CharField(max_length=255)),
                ('room_id', models.CharField(max_length=50)),
                ('periods_per_week', models.IntegerField(default=2)),
                ('is_continuous', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='timetable.timetablebatch')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory')], max_length=20)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='timetable.timetablebatch')),
            ],
            options={
                'db_table': 'room_allocations',
                'unique_together': {('batch', 'room_name')},
            },
        ),
        migrations.CreateModel(
            name='DayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('num_periods', models.IntegerField(default=6)),
                ('num_labs', models.IntegerField(default=0)),
                ('is_working_day', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_configs', to='timetable.timetablebatch')),
            ],
            options={
                'db_table': 'day_configs',
                'ordering': ['day'],
                'unique_together': {('batch', 'day')},
            },
        ),
    ]
