# Generated by Django 4.2.7 on 2026-05-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_add_timeslot_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day', 'slot_number']},
        ),
    ]
