# Generated by Django 4.2.7 on 2026-05-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timeslot_options'),
        ('timetable', '0003_timeslot_room_staff'),
    ]

    operations = [
    ]
