# Generated by Django 4.2.7 on 2026-05-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_merge_20260502_0837'),
        ('timetable', '0004_timeslot_subject_name'),
    ]

    operations = [
    ]
