# Generated by Django 4.2.7 on 2026-03-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_password',
            field=models.CharField(blank=True, default='', help_text='Temporary/initial plain-text password for dept credential view', max_length=128),
        ),
    ]
