# Generated by Django 4.2.7 on 2026-03-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', help_text='12-digit Aadhaar card number', max_length=12),
        ),
    ]
