# Generated by Django 4.2.7 on 2026-04-28 08:24

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notificationprefs_new_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_identifier', models.CharField(blank=True, default='', max_length=150)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('browser', models.CharField(blank=True, default='', max_length=120)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('login_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_login_activity',
                'indexes': [
                    models.Index(fields=['user', 'login_time'], name='student_log_user_id_login_ti_idx'),
                    models.Index(fields=['login_time'], name='student_log_login_ti_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DepartmentLoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_identifier', models.CharField(blank=True, default='', max_length=150)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('browser', models.CharField(blank=True, default='', max_length=120)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('login_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'department_login_activity',
                'indexes': [
                    models.Index(fields=['user', 'login_time'], name='department__user_id_login_ti_idx'),
                    models.Index(fields=['login_time'], name='department__login_ti_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='AdminLoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_identifier', models.CharField(blank=True, default='', max_length=150)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('browser', models.CharField(blank=True, default='', max_length=120)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('login_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_login_activity',
                'indexes': [
                    models.Index(fields=['user', 'login_time'], name='admin_login_user_id_login_ti_idx'),
                    models.Index(fields=['login_time'], name='admin_login_login_ti_idx'),
                ],
            },
        ),
    ]
