# Generated by Django 4.2.7 on 2026-04-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_login_activity_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminloginactivity',
            new_name='admin_login_user_id_6981ef_idx',
            old_name='admin_login_user_id_login_ti_idx',
        ),
        migrations.RenameIndex(
            model_name='adminloginactivity',
            new_name='admin_login_login_t_a7b86d_idx',
            old_name='admin_login_login_ti_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentloginactivity',
            new_name='department__user_id_5903b7_idx',
            old_name='department__user_id_login_ti_idx',
        ),
        migrations.RenameIndex(
            model_name='departmentloginactivity',
            new_name='department__login_t_182d8d_idx',
            old_name='department__login_ti_idx',
        ),
        migrations.RenameIndex(
            model_name='studentloginactivity',
            new_name='student_log_user_id_9232f8_idx',
            old_name='student_log_user_id_login_ti_idx',
        ),
        migrations.RenameIndex(
            model_name='studentloginactivity',
            new_name='student_log_login_t_0fe0f5_idx',
            old_name='student_log_login_ti_idx',
        ),
    ]
